title: Greek Musical Tradition
description: Greek Traditional & Byzantine Music Lessons
baseurl: "" # Keep empty for custom domains or root project
url: "https://greekmusicaltradition.com"
encoding: "utf-8"
